# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='planet_of_birth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planets.Planet'),
            preserve_default=False,
        ),
    ]
