# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('peoples', '0002_people_planet_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='hair_color',
            field=models.CharField(choices=[('None', 'none'), ('N/A', 'n/a'), ('Blond', 'blond'), ('Black', 'black'), ('Brown', 'brown'), ('White', 'white')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='movies',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
