# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0004_auto_20180501_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(choices=[('none', 'none'), ('n/a', 'n/a'), ('blond', 'blond'), ('black', 'black'), ('brown', 'brown'), ('white', 'white')], max_length=20),
        ),
    ]
